# http://travis-ci.org/#!/RDFLib/rdflib_zodb
language: python
# whitelist
branches:
  only:
    - master

python:
    - 2.6
    - 2.7

install:
    - python setup.py install

before_script:
    - flake8 --exit-zero rdflib_zodb

script:
    - nosetests
