# http://travis-ci.org/#!/RDFLib/rdflib_zodb
language: python
# whitelist
branches:
  only:
    - master

python:
    - 2.7

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=pypy
  - TOX_ENV=flake
  - TOX_ENV=cover

install:
    - pip install --use-mirrors --default-timeout 60 tox

script:
    - tox -e $TOX_ENV

after_script:
  - if [ $TOXENV == "cover" ]; then
    pip install --queiet --use-mirrors coveralls
    coveralls;
    fi
